import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

// Load fonts
const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: "400", subsets: ["latin"] });

// For SEO Optimization
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// children here, comes from the page component
// children is a prop that is passed to the layout component
// : Readonly<{ children: React.ReactNode; }> is a TypeScript type definition
// that specifies that the children prop is a React node
// And Readonly is a TypeScript utility type that makes the type read-only
// React.ReactNode is a TypeScript type that represents any node that can be rendered in React
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={poppins.className}>
        <div className="relative w-full flex justify-center items-center">
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
